scooters_store/scooters_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

scooters_store/store/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = "store"

urlpatterns = [

                  # Обработка шаблонов.
                  path('', views.index, name="index"),
                  path('profile/<slug:user_slug>/', views.profile, name='profile'),
                  path('update_profile/', views.update_user, name="update_profile"),

                  path('add_to_favorite/<slug:product_slug>/', views.add_to_favorite, name='add_to_favorite'),
                  path('remove_from_favorite/<slug:product_slug>/', views.remove_from_favorite,
                       name='remove_from_favorite'),
                  path('wishlist_detail/', views.wishlist_detail, name="wishlist_detail"),

                  path('product_detail/<slug:product_slug>/', views.product_detail, name='product_detail'),
                  path('products_by_category/<int:category_pk>/', views.products_list_by_category,
                       name='products_by_category'),

                  path('create_order/', views.create_order, name='create_order'),

                  path('get_cart/', views.cart_detail, name='cart_detail'),
                  path('add_to_cart/<slug:product_slug>/', views.cart_add, name='cart_add'),
                  path('remove_from_cart/<slug:product_slug>/', views.cart_remove, name='cart_remove'),
                  path('clean_cart/', views.clean_cart, name='cart_clean'),



                  path('register/', views.register_user, name='register'),
                  path('login/', views.login_user, name='login'),
                  path('logout/', views.logout_user, name='logout')

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scooters_store/store/models.py
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from .managers import CustomUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin


# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    """Собственная модель пользователя."""

    email = models.EmailField(verbose_name="Эл. почта", unique=True, blank=False,
                              help_text="Используйте формат: name@domain.com.")

    first_name = models.CharField(verbose_name="Имя", blank=True, null=True, max_length=30)
    last_name = models.CharField(verbose_name="Фамилия", blank=True, null=True, max_length=30)
    city = models.CharField(verbose_name="Город", blank=True, null=True, max_length=255)

    password = models.CharField(verbose_name="Пароль", blank=False, max_length=255)
    phone = models.CharField(verbose_name="Тел. номер", blank=True, max_length=12,
                             help_text="Используйте формат: +79770000000")
    slug = models.SlugField(verbose_name="Ссылка на профиль", unique=True)
    created_date = models.DateTimeField(verbose_name="Дата регистрации", auto_now_add=True)
    is_superuser = models.BooleanField(default=0, verbose_name="Админ")
    is_staff = models.BooleanField(default=0, verbose_name="Модератор")
    is_active = models.BooleanField(default=1, verbose_name="Активное / Нет")

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    class Meta:
        verbose_name_plural = "Пользователи"
        verbose_name = "Пользователя"

        ordering = ["-created_date"]

    def save(self, *args, **kwargs):
        """Переопределяем метод сохранения для автоматического создания поля slug из email,
        который затем становиться хеш-ключом."""

        self.slug = slugify(hash(self.email))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Собственный метод для получения ссылки на аккаунт пользователя."""
        return reverse("main:profile", kwargs={'slug': self.slug})

    def __str__(self):
        return self.email


class ProductsCategory(models.Model):
    """Модель для категорий товаров."""

    title = models.CharField(verbose_name="Наименование", blank=False, max_length=255)
    author = models.ForeignKey(User, verbose_name="Автор", on_delete=models.SET_NULL, null=True)
    created_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Категории товаров"
        verbose_name = "Категорию товара"

        ordering = ["-created_date"]

    def __str__(self):
        return self.title


class Product(models.Model):
    """Модель товаров."""

    title = models.CharField(verbose_name="Наименование", blank=False, max_length=255)
    price = models.DecimalField(verbose_name="Цена", max_digits=10, decimal_places=2)
    description = models.TextField(verbose_name="Описание", blank=False)
    count = models.IntegerField(verbose_name="Количество", blank=False)
    photo = models.ImageField(verbose_name="Фотография", blank=False, upload_to="media/products/")
    categories = models.ManyToManyField(ProductsCategory)
    created_date = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="Дата обновления", auto_now=True)
    is_active = models.BooleanField(verbose_name="Активно / Нет", default=True)
    author = models.ForeignKey(verbose_name="Кто добавил", to=User, on_delete=models.SET_NULL, null=True)
    slug = models.SlugField(verbose_name="Ссылка", unique=True)
    old_price = models.DecimalField(verbose_name="Старая цена", max_digits=10, decimal_places=2, null=True, blank=True)
    new = models.BooleanField(verbose_name="Новинка", default=0)
    top_sale = models.BooleanField(verbose_name="Лидер продаж", default=0)

    class Meta:
        verbose_name_plural = "Товары"
        verbose_name = "Товар"

        ordering = ["-created_date"]

    def save(self, *args, **kwargs):
        self.slug = slugify(hash(self.title + str(self.created_date)))
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("store:product_detail", kwargs={'product_slug': self.slug})

    def __str__(self):
        return self.title


class Favorite(models.Model):
    """Модель избранных товаров."""

    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="Товар", on_delete=models.CASCADE)
    created_date = models.DateTimeField(verbose_name="Дата добавления", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Избранные товары"
        verbose_name = "Избранный товар"

        ordering = ["-created_date"]

    def __str__(self):
        return self.product.title


class Store(models.Model):
    """Модель магазинов."""

    title = models.CharField(verbose_name="Название магазина", blank=False, max_length=255)
    address = models.CharField(verbose_name="Адрес магазина", blank=False, max_length=255)
    created_date = models.DateTimeField(verbose_name="Дата добавления", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Магазины"
        verbose_name = "Магазин"

        ordering = ["-created_date"]

    def __str__(self):
        return self.title


class Order(models.Model):
    """Модель для сохранения заказов."""

    order_status = (
        ('1', 'Собирается'),
        ('2', 'Доставляется'),
        ('3', 'Доставлен в ПВЗ'),
        ('4', 'Завершён'),
        ('5', 'Отменён')
    )

    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.SET_NULL, null=True, blank=True)
    first_name = models.CharField(verbose_name='Имя заказчика', null=True, blank=True, max_length=255)
    email = models.EmailField(verbose_name="Эл. почта", null=True)
    last_name = models.CharField(verbose_name='Фамилия заказчика', null=True, blank=True, max_length=255)
    city = models.CharField(verbose_name='Город заказчика', null=True, blank=True, max_length=255)
    products = models.ManyToManyField(Product, verbose_name="Товары")
    phone = models.CharField(verbose_name="Телефон", blank=True, null=True, max_length=255)
    address = models.CharField(verbose_name="Адрес доставки", null=True, max_length=255, blank=True)
    status = models.CharField(verbose_name="Статус заказа", choices=order_status, blank=False, max_length=255)
    price = models.DecimalField(verbose_name="Стоимость заказа", max_digits=10, decimal_places=2, null=True)
    comment = models.TextField(verbose_name="Комментарий к заказу", null=True, blank=True)
    created_date = models.DateTimeField(verbose_name="Дата заказа", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Заказы"
        verbose_name = "Заказ"

        ordering = ["-created_date"]

    def save(self, *args, **kwargs):
        # Получает общую стоимость заказа.
        super().save(*args, **kwargs)
        self.price = sum(product.price for product in self.products.all())

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('', kwargs={'slug': self.pk})

scooters_store/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.hashers import make_password
from django.http.response import JsonResponse
from .models import User, Product, Favorite, ProductsCategory, Order
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .cart import Cart
from .wishlist import WishList
import json


# Create your views here.


def index(request):
    """Представление главное страницы."""

    # Выводим только активные товары, и товары, у которых количество больше 0.
    new_products = Product.objects.filter(is_active=True, count__gt=0, new=1)
    top_sale_products = Product.objects.filter(is_active=True, count__gt=0, top_sale=1)

    categories = ProductsCategory.objects.all()

    context = {
        'new_products': new_products,
        'top_sale_products': top_sale_products,
        'categories': categories,
    }

    return render(request, 'index.html', context=context)



def profile(request, user_slug: str):
    """Представление профиля пользователя."""

    user = get_object_or_404(User, slug=user_slug)
    favorites_list = Favorite.objects.filter(user=user)
    orders_list = Order.objects.filter(user=user)
    categories = ProductsCategory.objects.all()

    context = {
        'user': user,
        'favorites_list': favorites_list,
        'orders_list': orders_list,
        'categories': categories
    }

    return render(request, 'profile.html', context=context)


def update_user(request):
    """Обновляет данные пользователя."""

    if request.method == "POST" and request.user.is_authenticated:
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        city = request.POST.get('city')
        phone = request.POST.get('phone')

        user_for_update = User.objects.get(email=request.user.email)

        user_for_update.first_name = first_name
        user_for_update.last_name = last_name
        user_for_update.city = city
        user_for_update.phone = phone

        user_for_update.save()

        return redirect(f'http://127.0.0.1:8081/profile/{user_for_update.slug}/')




def product_detail(request, product_slug):
    """Представление детальной информации о товаре."""

    product = get_object_or_404(Product, slug=product_slug)
    categories = ProductsCategory.objects.all()

    context = {
        'product': product,
        'categories': categories
    }

    return render(request, 'product_detail.html', context=context)


def products_list_by_category(request, category_pk: int):
    """Возвращает товары по выбранной категории."""

    category = ProductsCategory.objects.get(pk=category_pk)
    products = Product.objects.filter(categories=category)
    categories = ProductsCategory.objects.all()

    return render(request, 'products_by_categories.html', {'products': products,
                                                           'categories': categories,
                                                           'actual_category': category})


def register_user(request):
    """Представление регистрации пользователя."""

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = User(email=email, password=make_password(password))

        try:
            user.save()
            return redirect('/')
        except Exception as e:
            return JsonResponse({'message': 'Произошла ошибка при попытке создать пользователя!',
                                 'status_code': 403})


def login_user(request):
    """Представление авторизации пользователя."""

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        print(email, password)

        user = authenticate(username=email, password=password)

        if not user:
            return JsonResponse({'message': 'Вы ввели неверные данные или такого пользователя не существует!',
                                 'status_code': 403})

        if user.is_active:
            login(request, user)
            return redirect("/")


def logout_user(request):
    """Представление выхода пользователя из системы."""

    logout(request)

    return redirect("/")


def create_order(request):
    """Представление создающее заказ."""

    if request.method == "POST":

        data = json.loads(request.body)

        products = [Product.objects.get(slug=request_product) for request_product in data['products']]

        order = Order(price=data['total_price'], address=data['address'],
                      first_name=data['first-name'], last_name=data['last-name'], city=data['city'],
                      phone=data['tel'], email=data['email'], comment=data['comment'])

        if request.user.is_authenticated:
            order.user = request.user

        order.save()
        order.products.set(products)

        try:
            order.save()
            return JsonResponse({'message': 'Ваш заказ успешно создан, ожидайте звонка на указанный телефон!',
                                 'status_code': 200,
                                 'order_id': order.pk})
        except Exception as e:
            return JsonResponse({'message': 'При попытке совершить заказ произошла ошибка! Повторите попытку позже!',
                                 'status_code': 403,
                                 'error_detail': e})

    if request.method == "GET":
        categories = ProductsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'order_create_page.html', context=context)


@require_POST
def add_to_favorite(request, product_slug: str):
    """Представление добавления товара в избранное."""

    wishlist = WishList(request)
    product = get_object_or_404(Product, slug=product_slug)
    wishlist.add(product)

    return JsonResponse(wishlist.wishlist)


@require_POST
def remove_from_favorite(request, product_slug: str):
    """Представление, удаляющее товар из избранного."""

    wishlist = WishList(request)
    product = get_object_or_404(Product, slug=product_slug)
    wishlist.remove(product)

    return JsonResponse(wishlist.wishlist)


def wishlist_detail(request):
    """Возвращает список желаемого."""

    wishlist = WishList(request)
    return JsonResponse(wishlist.wishlist)


@require_POST
def cart_add(request, product_slug: str):
    """Представление добавляющее товар в корзину."""

    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)

    cart.add(product)
    cart.cart['total_price'] = int(cart.get_total_price())

    return JsonResponse(cart.cart)


@require_POST
def cart_remove(request, product_slug: str):
    """Представление удаляющее товар из корзины."""

    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)
    cart.remove(product)

    cart.cart['total_price'] = int(cart.get_total_price())

    return JsonResponse(cart.cart)


def cart_detail(request):
    """Представление выводящее корзину покупок на страницу"""

    cart = Cart(request)
    cart.cart['total_price'] = int(cart.get_total_price())
    cart.cart['product_len'] = len(cart)

    return JsonResponse(cart.cart)


@require_POST
def clean_cart(request):
    """Представление очищающие корзину."""

    cart = Cart(request)
    cart.clear()

    return JsonResponse(cart.cart)

scooters_store/store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>Интернет магазин</title>

 		<!-- Google font -->
 		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

 		<!-- Bootstrap -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

 		<!-- Slick -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
 		<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

 		<!-- nouislider -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

 		<!-- Font Awesome Icon -->
 		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

 		<!-- Custom stlylesheet -->
 		<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

 		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
 		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
 		<!--[if lt IE 9]>
 		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
 		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 		<![endif]-->

    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +7-977-222-32-32</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
						<li><a href="#"><i class="fa fa-map-marker"></i>Москва</a></li>
					</ul>
					<ul class="header-links pull-right">
						{% if request.user.is_authenticated %}
						<li><a href="{% url 'store:profile' user_slug=request.user.slug %}"><i class="fa fa-user-o"></i>Профиль</a></li>
						<li><a href="{% url 'store:logout' %}"><i class="fa fa-sign-out"></i>Выйти</a></li>
						{% else %}
						<li><a href="#" class="auth_modal_open_button"><i class="fa fa-sign-in"></i>Войти / Зарегистрироваться</a></li>
						{% endif %}

						<!-- Модалка авторизации  -->
						<div id="auth_modal" class="auth_modal swiper">
							<div class="auth_modal_slide__buttons">
								<button class="auth_modal__buttons button-prev">Регистрация</button>
								<button class="auth_modal__buttons button-next">Вход</button>
							</div>
							<div id="auth_modal__wrapper" class="auth_modal__wrapper swiper-wrapper">
								<div id="auth_modal__slide" class="auth_modal__slide swiper-slide">
									<form method="post" enctype="multipart/form-data" action="{% url 'store:register' %}">
										{% csrf_token %}
										<div class="modal_slide_header">
											<h3>Регистрация</h3>
										</div>
										<div class="modal_slide_body">
											<div class="auth_modal_inputs_item">
												<input type="email" required placeholder="Email" name="email">
											</div>
											<div class="auth_modal_inputs_item">
												<input type="password" name="password" placeholder="Пароль" required>
											</div>
										</div>
										<div class="modal_slide_footer">
											<button class="auth_modal__buttons" type="submit">Зарегистрироваться</button>
										</div>
									</form>
								</div>
								<div id="auth_modal__slide" class="auth_modal__slide swiper-slide">
									<form method="post" enctype="multipart/form-data" action="{% url 'store:login' %}">
										{% csrf_token %}
										<div class="modal_slide_header">
											<h3>Вход</h3>
										</div>
										<div class="modal_slide_body">
											<div class="auth_modal_inputs_item">
												<input type="email" name="email" placeholder="Email" required>
											</div>
											<div class="auth_modal_inputs_item">
												<input type="password" name="password" required placeholder="Пароль">
											</div>
										</div>
										<div class="modal_slide_footer">
											<button class="auth_modal__buttons" type="submit">Войти</button>
										</div>
									</form>
								</div>
							</div>
						</div>
						<!-- /Модалка авторизации -->

					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="#" class="logo">
									<img src="" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6" style="visibility: hidden;">
							<div class="header-search">
								<form>
									<select class="input-select">
										<option value="0">Все категории</option>

<!--										<option value="1">Category 01</option>-->
<!--										<option value="1">Category 02</option>-->
									</select>
									<input class="input" placeholder="Название товара">
									<button class="search-btn">Поиск</button>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
								<!-- Wishlist -->
								<div>
									<a href="#" class="wishlist_open_button">
										<i class="fa fa-heart-o"></i>
										<span>Избранное</span>
										<!-- <div class="qty wishlist_len"></div> -->
									</a>
									<div class="wishlist_wrapper">
										<div class="wishlist_list"></div>
									</div>
								</div>
								<!-- /Wishlist -->

								<!-- Cart -->
								<div class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										<span>Корзина</span>

										<div class="qty cart_len"></div>

									</a>
									<div class="cart-dropdown">
										<div class="cart-list">
										</div>
										<div class="cart-summary">

										</div>
										<div class="cart-btns">
<!--											<a href="#">View Cart</a>-->
											<a href="{% url 'store:create_order' %}">Оформить заказ  <i class="fa fa-arrow-circle-right"></i></a>
										</div>
									</div>
								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
<!--						Тут будут выводиться категории, которые представлены на сайте-->
						<li class="active"><a href="{% url 'store:index' %}">Главная</a></li>
						{% for category in categories %}
						<li><a href="{% url 'store:products_by_category' category_pk=category.pk%}">{{category.title}}</a></li>
						{% endfor %}
<!--						<li><a href="#">Categories</a></li>-->
<!--						<li><a href="#">Laptops</a></li>-->
<!--						<li><a href="#">Smartphones</a></li>-->
<!--						<li><a href="#">Cameras</a></li>-->
<!--						<li><a href="#">Accessories</a></li>-->
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		{% block content %}
		{% endblock %}


		<!-- FOOTER -->
		<footer id="footer">
			{% csrf_token %}
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">О нас</h3>
								<p>Небольшой магазин электроники</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>Москва</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+7-977-222-32-32</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Сервисы</h3>
								<ul class="footer-links">
									<li><a href="#">Мой аккаунт</a></li>
									<li><a href="#">Посмотреть корзину</a></li>
									<li><a href="#">Избранное</a></li>
								</ul>
							</div>
						</div>
					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>


						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->





		<!-- jQuery Plugins -->
		<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
		<script>
			let swiper = new Swiper(".swiper", {
				navigation: {
					nextEl: ".button-next",
					prevEl: ".button-prev",
				  },
			});
		  </script>
		  <script src="{% static 'js/auth_modal.js' %}"></script>

		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/slick.min.js' %}"></script>
		<script src="{% static 'js/nouislider.min.js' %}"></script>
		<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
		<script src="{% static 'js/cart.js' %}"></script>
		<script src="{% static 'js/favorite.js' %}"></script>

	</body>
</html>